name: Conda

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2016, macos-latest]
        python-version: [3.8, 3.9]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      PYTHONIOENCODING: utf-8
    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache conda
        uses: actions/cache@v1
        with:
          path: ~/conda_pkgs_dir
          key: ${{matrix.os}}-conda-pkgs-${{hashFiles('**/conda.recipe/meta.yaml')}}

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
          use-only-tar-bz2: true
          auto-activate-base: true

      #- name: Prepare
        #run: conda install conda-build conda-verify

      #- name: Build
        #run: conda build conda.recipe

      - name: Install
        run: |
          conda install pyre2 pytest
          # was: conda install -c ${CONDA_PREFIX}/conda-bld/ pyre2

      - name: Test
        run: |
          python -m pytest -v -m "not subscript" .
