name: Build

on:
  workflow_dispatch:
  pull_request:
  #push:
    #branches:
      #- master

jobs:
  build_wheels:
    name: Platform wheels for Python 3.6 to 3.11
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.10'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.3
        env:
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-* cp311-*
          CIBW_ARCHS_MACOS: auto universal2
          CIBW_ARCHS_LINUX: auto64
          CIBW_ARCHS_WINDOWS: auto64
          CIBW_SKIP: "*musllinux* cp3{6,7}-macosx_universal2"
          CIBW_TEST_SKIP: "*-macosx_universal2:arm64"
          CIBW_TEST_REQUIRES: ''
          CIBW_TEST_COMMAND: ''
          USE_PYBIND11_PKG: OFF

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build sdist
        run: |
          pip install build
          python -m build -s .

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz

  check_artifacts:
    needs: [build_sdist, build_wheels]
    defaults:
      run:
        shell: bash
    name: Check artifacts are correct
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      # note wheels should be in subdirectory <upload_name>
      - name: Check number of downloaded artifacts
        run: ls -l dist
